name: genesis
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pip=24.2
  - pysocks=1.7.1
  - python=3.9.21
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - toml=0.10.2
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.17.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - black==24.10.0
      - click==8.1.8
      - coacd==1.0.5
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.1.1
      - deprecated==1.2.15
      - dill==0.3.9
      - etils==1.5.2
      - fonttools==4.55.3
      - freetype-py==2.5.1
      - fsspec==2024.12.0
      # genesis-world==0.2.1
      - glfw==2.8.0
      - grpcio==1.68.1
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - imgui==2.0.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libigl==2.5.1
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.23.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - moviepy==2.1.1
      - mujoco==3.2.5
      - mypy-extensions==1.0.0
      - numba==0.60.0
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - openexr==3.3.2
      - packaging==24.2
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pooch==1.8.2
      - proglog==0.1.10
      - protobuf==5.29.2
      - psutil==6.1.1
      - pybind11==2.13.6
      - pybind11-global==2.13.6
      - pycollada==0.8
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygel3d==0.5.2
      - pyglet==2.0.20
      - pygltflib==1.16.0
      - pygments==2.18.0
      - pymeshlab==2023.12.post2
      - pyopengl==3.1.7
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pyvista==0.44.2
      - rich==13.9.4
      - scikit-image==0.24.0
      - scipy==1.13.1
      - scooby==0.10.0
      - screeninfo==0.8.1
      - six==1.17.0
      - taichi==1.7.3
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tetgen==0.6.4
      - tifffile==2024.8.30
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - vtk==9.3.1
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - zipp==3.21.0
